apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: esouza/k8s-argocd-demo
  newTag: 70ea669080a32ef31342945bf5e91bba4a4c064f
