name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-argocd-demo:latest,${{ secrets.DOCKERHUB_USERNAME }}/k8s-argocd-demo:${{ github.sha }}

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      
      - name: Update Kubernetes resources
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image goserver=$DOCKERHUB_USERNAME/k8s-argocd-demo:${{ github.sha }}

      - name: Commit updated manifests
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add k8s
          git commit -m "Bump image to ${{ github.sha }}" || echo "No changes to commit"

      - name: Push changes back to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master